# Prompt
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_CHAR_SYMBOL='# '
SPACESHIP_CHAR_COLOR_SUCCESS='#ffdd33'
SPACESHIP_CHAR_COLOR_FAILURE='#ffdd33'
SPACESHIP_CHAR_COLOR_SECONDARY='#ffdd33'

# Display time
SPACESHIP_TIME_FORMAT='%D{%H:%M}'
SPACESHIP_TIME_COLOR='#ffffff'
SPACESHIP_TIME_SHOW=true

# Battery
SPACESHIP_BATTERY_ASYNC=false
SPACESHIP_BATTERY_SHOW=always

# Directory
SPACESHIP_DIR_PREFIX=''
SPACESHIP_DIR_COLOR='#ffdd33'

# Git
SPACESHIP_GIT_BRANCH_COLOR='#ffdd33'
SPACESHIP_GIT_STATUS_COLOR='#96a6c8'
